name: test_github

on:
  schedule:
      - cron: '5 * * * *' # run at 10th day of every month at 20:00 GMT+7
  workflow_dispatch:

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tv_requirements.txt

      - name: execute ms_updater.py script
        run: python test.py
      
      - name: Commit and Push Changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "GitHub Actions Results added"
            git push-m "Saving data to csv due to error in ms_updater.py"
            git push
          else
            echo "No changes to commit."
          fi
          
